service: import-service
frameworkVersion: '2'
variablesResolutionMode: 20210219


provider:
  name: aws
  runtime: nodejs14.x
  stage: 'dev'
  region: eu-west-1
  # environment:
  #   SQS_URL: ${cf:product-service-dev.SQS_URL}

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::mybuckettask5"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::mybuckettask5/*"
    # - Effect: "Allow"
    #   Action: "sqs:*"
    #   Resource:
    #     - Fn::GetAtt: [ catalogItemsQueue, Arn ]

  # environment:
  #   SQS_URL:
  #     Ref: catalogItemsQueue

# resources:
#   Resources:
#     catalogItemsQueue:
#       Type: AWS::SQS::Queue
#       Properties:
#         QueueName: cvs-sqs

#     createProductTopic:
#       Type: AWS::SNS::Topic
#       Properties:
#         TopicName: notify-about-products



plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    dotenvVars: ${file(configs.js)}

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true

  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: mybuckettask5
          event: s3:ObjectCreated:*
          rules: 
            - prefix: 'uploaded/'
          existing: true
  
